//= require jquery
//= require bootstrap-sprockets
//= require bootstrap
//= require vendor/_alertify
//= require_validate
//= require_age-gate
//= require_code-gate
//= require_scroll
//= require vendor/_mobiscroll
//= require_tree .
